.\" $Id: yyextract.1,v 1.12 1997/11/22 18:39:00 sandro Exp $
.Dd November 22, 1997
.Os
.Dt YYEXTRACT 1
.Sh NAME
.Nm yyextract
.Nd extract grammar rules from a yacc grammar
.Sh SYNOPSIS
.Nm yyextract
.Op Fl behyV
.Op Fl o Ar file
.Op Fl w Ar cols
.Op Ar
.Sh DESCRIPTION
The
.Nm yyextract
utility
extracts the grammar rules from a yacc grammar.
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl b
Select the Backus-Naur Form (BNF) for the output.
.It Fl e
Select the Extended Backus-Naur Form (EBNF) for the output.
.It Fl h
Output in HTML format.
.It Fl o
Set the output destination to
.Ar file .
.It Fl w
Set the width limit of the output (this sets only the width of the %token
header).
.It Fl y
Select the yacc format for the output. This is the default format.
.It Fl V
Print version information on standard output then exit.
.El
.Sh NOTES
The Extended Backus-Naur Form (EBNF) is like the Backus-Naur Form (BNF)
but with the empty rules translated with the zero-or-one
operator (within the brackets '[' and ']').
.Sh AUTHORS
Sandro Sigala (ssigala@globalnet.it)
