.\" $Id: cweave.1,v 1.11 1997/11/22 18:38:58 sandro Exp $
.Dd November 22, 1997
.Os
.Dt CTANGLE 1
.Sh NAME
.Nm cweave
.Nd extract LaTeX formatting commands from a literate source file
.Sh SYNOPSIS
.Nm cweave
.Op Fl hV
.Op Fl o Ar file
.Op Fl t Ar width
.Op Ar
.Sh DESCRIPTION
The
.Nm cweave
utility
extracts the LaTeX formatting commands from a literate source file.
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl h
Highlight the source code with different fonts.
.It Fl o
Set the output destination to
.Ar file .
.It Fl t
Set the tabulation width to
.Ar width .
.It Fl V
Print version information on standard output then exit.
.El
.Sh SEE ALSO
.Xr ctangle 1 ,
.Xr cweb 5
.Sh AUTHORS
Sandro Sigala (ssigala@globalnet.it)
