.\" $Id: ctangle.1,v 1.10 1997/11/22 18:38:50 sandro Exp $
.Dd November 22, 1997
.Os
.Dt CTANGLE 1
.Sh NAME
.Nm ctangle
.Nd extract code from a literate source file
.Sh SYNOPSIS
.Nm ctangle
.Op Fl V
.Op Fl o Ar file
.Op Ar
.Sh DESCRIPTION
The
.Nm ctangle
utility
extracts the code from a literate source file.
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl o
Set the output destination to
.Ar file .
.It Fl V
Print version information on standard output then exit.
.El
.Sh SEE ALSO
.Xr cweave 1 ,
.Xr cweb 5
.Sh AUTHORS
Sandro Sigala (ssigala@globalnet.it)
