.\" $Id: cweb.5,v 1.7 1997/11/22 18:38:50 sandro Exp $
.Dd November 22, 1997
.Os
.Dt CWEB 5
.Sh NAME
.Nm cweb
.Nd literate programming
.Sh DESCRIPTION
A cweb file is composed by sections of LaTeX commands and sections
of C source code.  The switching between the two section is possible
with the
.Nm @@
token sequence.  The default section is LaTeX.
.Pp
The directives that can be inserted in the LaTeX section are as follows:
.Bl -tag -width indent
.It @decl Op Ar text
Declare a new section of code (or continue an old one) with the title
.Nm text .
.It @ref Op Ar text
Reference a section of code with the title
.Nm text .
.El
.Sh SEE ALSO
.Xr ctangle 1 ,
.Xr cweave 1
.Sh AUTHORS
Sandro Sigala (ssigala@globalnet.it)
