.\" $Id: cinfoc.1,v 1.17 1997/11/22 18:38:41 sandro Exp $
.Dd November 22, 1997
.Os
.Dt CINFOC 1
.Sh NAME
.Nm cinfoc
.Nd cinfo database compiler
.Sh SYNOPSIS
.Nm cinfoc
.Op Fl \&dV
.Ar
.Sh DESCRIPTION
The
.Nm cinfoc
utility is the standard cinfo database compiler.
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl d
Turn debug mode on.
.It Fl V
Print version information on standard output then exit.
.El
.Sh SEE ALSO
.Xr cinfo 1 ,
.Xr cinfodc 1 ,
.Xr cinfodb 5
.Sh AUTHORS
Sandro Sigala (ssigala@globalnet.it)
