.\" $Id: cunloop.1,v 1.4 1997/11/22 18:38:55 sandro Exp $
.Dd November 22, 1997
.Os
.Dt CUNLOOP 1
.Sh NAME
.Nm cunloop
.Nd unloop C loops
.Sh SYNOPSIS
.Nm cunloop
.Op Fl V
.Op Fl o Ar file
.Op Fl p Ar prefix
.Op Ar
.Sh DESCRIPTION
The
.Nm cunloop
utility
unloops the C language loop and branch instructions
.Nm while , do , for, if
into a sequence of
.Nm goto
instuctions to render the source file unreadable.
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl o
Set the output destination to 
.Ar file .
.It Fl p
Set the identifier prefix for generating the labels.
.It Fl V
Print version information on standard output then exit.
.El
.Sh SEE ALSO
.Xr cobfusc 1 ,
.Xr indent 1
.Sh AUTHORS
Sandro Sigala (ssigala@globalnet.it)
